import_market_data_afternoon:
  cron: "30 7 * * 1-5" # 3:30 PM Beijing time (7:30 AM UTC) Monday through Friday
  class: "ImportMarketDataJob"
  queue: "scheduled"
  description: "Imports market data daily at 3:30 PM Beijing time (after A-share market close)"
  args:
    mode: "full"
    clear_cache: false

import_market_data_evening:
  cron: "30 8 * * 1-5" # 4:30 PM Beijing time (8:30 AM UTC) Monday through Friday
  class: "ImportMarketDataJob"
  queue: "scheduled"
  description: "Imports market data daily at 4:30 PM Beijing time (after H-share market close)"
  args:
    mode: "full"
    clear_cache: false

realtime_market_data:
  cron: "* * * * 1-5" # Every minute Monday through Friday
  class: "RealtimeMarketDataJob"
  queue: "scheduled"
  description: "Updates real-time market data during A-share and H-share market hours"
  
clean_syncs:
  cron: "0 * * * *" # every hour
  class: "SyncCleanerJob"
  queue: "scheduled"
  description: "Cleans up stale syncs"

run_security_health_checks:
  cron: "0 2 * * 1-5" # 2:00 AM EST / 3:00 AM EDT (NY time) Monday through Friday
  class: "SecurityHealthCheckJob"
  queue: "scheduled"
  description: "Runs security health checks to detect issues with security data"
